name: Jest CI

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]
  pull_request:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        workdir: ./backend/
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Setup dotenv
        run: |
          echo 'NODE_ENV = "dev"'' > .env && echo 'MONGO_URI = "${{ secrets.MONGO_DEV }}"' >> .env
        workdir: ./backend/
      - name: Install dependencies
        run: yarn install
        workdir: ./backend/
      - name: Run Tests
        workdir: ./backend/
        run: yarn test
